=== coderbyheart/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="usergroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="nonEmptyString">
					<xs:annotation>
						<xs:documentation>Vollständiger Name der Usergroup in Langfassung,
							z.B. Python UserGroup RheinMain
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="nickname" type="nonEmptyString" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="nonEmptyString">
					<xs:annotation>
						<xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
							ausführlich sein.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="url" type="xs:anyURI">
					<xs:annotation>
						<xs:documentation>Die URL der Homepage der Usergroup.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="tags">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tag" type="xs:token" maxOccurs="3"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contact" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mailinglist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="label" type="nonEmptyString"></xs:element>
										<xs:element name="description" type="nonEmptyString" minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="email" minOccurs="0" type="email"></xs:element>
							<xs:element name="twitter" minOccurs="0" type="twitter"></xs:element>
							<xs:element name="hashtag" minOccurs="0" type="hashtag"></xs:element>
							<xs:element name="facebook" minOccurs="0" type="facebook"></xs:element>
							<xs:element name="googleplus" minOccurs="0" type="googleplus"></xs:element>
							<xs:element name="xing" minOccurs="0" type="xing"></xs:element>
							<xs:element name="irc" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="server" type="xs:anyURI"></xs:element>
										<xs:element name="room" type="nonEmptyString"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="xmpp" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="server" type="xs:anyURI"></xs:element>
										<xs:element name="room" type="nonEmptyString"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="schedule" minOccurs="0">
					<xs:complexType>
						<xs:annotation>
							<xs:documentation>Liefert Information zu den nächsten Treffen der
								UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
								werden, oder die Meetings werden manuell konfiguriert.
							</xs:documentation>
						</xs:annotation>
						<xs:choice>
							<xs:element name="ical" type="xs:anyURI"></xs:element>
							<xs:element name="meeting" maxOccurs="unbounded" type="meeting"></xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="sponsors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sponsor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="nonEmptyString"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="photocredits" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="logo" type="nonEmptyString"
								minOccurs="0"></xs:element>
							<xs:element name="group" type="nonEmptyString"
								minOccurs="0"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="email">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für E-Mail Adressen
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="twitter">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Twitter-Handles
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="@[a-zA-Z0-9_]{1,15}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="hashtag">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Hashtags
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#[a-zA-Z0-9]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="facebook">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf facebook.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.facebook\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="xing">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf xing.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.xing\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="googleplus">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf Google+
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://plus\.google\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
	<xs:simpleType name="nonEmptyString">
		<xs:annotation>
			<xs:documentation>Ein nicht-leerer String</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="meeting">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Meetings (zukünftige
				und vergangene)
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="time" type="xs:dateTime"></xs:element>
			<xs:element name="name" type="nonEmptyString"></xs:element>
			<xs:element name="description" type="nonEmptyString" minOccurs="0"></xs:element>
			<xs:element name="url" type="xs:anyURI" minOccurs="0"></xs:element>
			<xs:element name="location" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. OFfenraum Coworking Space
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="description" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. OFfenraum ist ein Coworking Space im
									Rhein-Main-Gebiet südlich von Frankfurt in Offenbach am Main,
									in der Nähe des Hauptbahnhofs, Hassia Fabrik und
									Stadtkrankenhaus.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="url" type="xs:anyURI" minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. http://offenraum.de/#lage
								</xs:documentation>
							</xs:annotation>
						</xs:element>
                        <xs:element name="twitter" type="twitter" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>z.B. @OFfenraum
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
						<xs:element name="publictransport" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Regionalbahn HBf Offenbach. S1, S2, S8,
									S9 Offenbach Markplatz. Bus 104 Haydnstraße.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="street" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. Senefelderstr. 63</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="zip" type="plz">
							<xs:annotation>
								<xs:documentation>z.B. 63069</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="city" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. Offenbach</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="region" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Hessen</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="country" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Deutschland</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="plz">
		<xs:annotation>
			<xs:documentation>Eine deutsche PLZ</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="10000"></xs:minInclusive>
			<xs:maxInclusive value="99999"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== coderbyheart/ugrm-data/usergroup/bcrm.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" female="false">
    <name>BarCamp RheinMain</name>
    <nickname>BCRM</nickname>
    <description>Ein BarCamp ist eine andere Form von Konferenz.
        Im Gegensatz zu den gewöhnlichen Fachkonferenzen erfolgt der Wissensaustausch bei BarCamps unentgeltlich und
        gegenseitig. Das heißt, es gibt keine designierten Sprecher, die Beiträge werden allesamt von den Besuchern
        gestaltet und auch gehalten.

        Auch eine Themenvorgabe wird bewusst vermieden, fachfremde Teilnehmer und Vorträge sind sogar erwünscht. Die
        Organisatoren stellen lediglich Termin und Räumlichkeiten zur Verfügung, um alles andere kümmern sich die
        Teilnehmer selbst.
    </description>
    <url>http://www.barcamp-rheinmain.de/</url>
    <tags>
        <tag>BarCamp</tag>
    </tags>
    <contact>
        <email>info@netzkultur-rheinmain.de</email>
        <twitter>@bc_rm</twitter>
        <hashtag>#bcrm13</hashtag>
        <facebook>http://www.facebook.com/BarCampRheinMain</facebook>
        <googleplus>https://plus.google.com/u/0/106777532284423884475/posts</googleplus>
    </contact>
    <schedule>
        <meeting>
            <time>2013-11-23T08:00:00</time>
            <name>BarCamp RheinMain Dieburg 2013</name>
            <url>http://dieburg2013.barcamp-rheinmain.de/</url>
            <location>
                <name>Mediencampus der Hochschule Darmstadt</name>
                <url>http://mediencampus.h-da.de/campus/anfahrt/</url>
                <street>Max-Planck-Straße 2</street>
                <zip>64807</zip>
                <city>Dieburg</city>
            </location>
        </meeting>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/cccda.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Chaos Darmstadt</name>
    <description>Chaos Darmstadt ist die örtliche Vertretung des Chaos in Darmstadt. Wir sind "ErfA"-Kreis des CCC und
        eine Hochschulgruppe der TU Darmstadt. (Bei uns sind aber natürlich auch nicht studierende Personen herzlich
        willkommen!) Im Rhein-Main-Gebiet fördern wir den Zusammenhalt und Erfahrungsaustausch der Computer- und
        Chaostreffs (MetaRheinMain). Wir treffen uns jeden Dienstag ab 19:00 Uhr zum Open Chaos in unserem Hackspace 
	- aktueller Arbeitsname "W17" - im dritten Obergeschoss der Wilhelminenstraße 17 in 64283 Darmstadt. Für Anfahrtsbeschreibungen frage bitte den
        Routingdienstleister deines geringsten Misstrauens. Falls du unsicher bist, ob der Raum offen ist, schau einfach auf unserer Webseite nach.
    </description>
    <url>https://chaos-darmstadt.de/</url>
    <tags>
		<tag>Technik-Kultur-Gesellschaft</tag>
        	<tag>CCC</tag>
		<tag>Hackerspace</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>https://lists.darmstadt.ccc.de/mailman/listinfo/public</url>
            <label>Unsere große offene Liste. Diese Mailingliste ist offen für alle, die sich im Umfeld von Darmstadt (z.B. über ihre Projekte) austauschen möchten.</label>
        </mailinglist>
        <twitter>@chaosdarmstadt</twitter>
    </contact>
 <defaultmeetinglocation>
	<name>Hackspace Chaos Darmstadt - W17</name>
	<description>Unsere Treffen finden in unserem Hackspace mit aktuellem Arbeitsname "W17" statt. Diese befindet sich im 3.OG der Wilhelminenstraße 17 in 64283 Darmstadt. Wir empfehlen die Anreise mit dem Fahrrad oder öffentlichen Verkehrsmitteln.</description>
    <url>https://www.chaos-darmstadt.de/hackspace.html</url>
    <publictransport>
        Bei der Anfahrt mit öffentlichen Verkehrsmitteln ist es am einfachsten mit dem Bus oder der Straßenbahn bis zum Luisenplatz zu fahren und von dort zu laufen. Der Luisenplatz ist der zentrale Umstiegspunkt in Darmstadt und wird von fast allen Linien angefahren</publictransport>
 <street>Wilhelminenstraße 17</street>
 <zip>64283</zip>
 <city>Darmstadt</city>
 </defaultmeetinglocation>
 <schedule usedefaultmeetinglocation="true">
     <ical>https://davical.darmstadt.ccc.de/public.php/cda/public/</ical>
 </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/codingnight.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Coding Night</name>
    <description markdown="true">Mit der *Coding Night* möchte ich Codern, angefangen vom Rookie bis zum Pro, eine
        Möglichkeit bieten, sich mit etwas Neuem zu beschäftigen, etwas auszuprobieren und das in einer lockeren
        Atmosphäre.

        Du hast also während der *Coding Night* die Gelegenheit, eine neue Programmiersprache, ein Framework, eine
        IDE oder eine Programmiertechnik gemeinsam mit anderen Codern auszuprobieren.

        Wenn das Projekt an dem du mit der Gruppe arbeitest, etwas größeres ist, dann kannst du dieses auch über die
        nächsten Wochen und Monate gemeinsam mit deiner Gruppe verfolgen. Vielleicht entwickelt sich daraus ein
        Team, was sich dann sogar zu einem Startup entwickelt.

        Wie du siehst, ist die *Coding Night* genau das richtige für dich!

        **Das geile dabei: du erarbeitest dir in der Gruppe neue Skills und lernst gleichzeitig auch neue Coder
        kennen.**

        Das primäre Ziel einer *Coding Night* sollte stets LERNEN sein. Egal ob das jetzt eine neue
        Programmiersprache oder ein Framework ist. Du solltest nachdem du die *Coding Night* verlassen hast immer mehr
        wissen, als davor. :). Zusätzlich wäre es super, wenn du einen neuen Coder kennen lernst.


        **Wie läuft so eine *Coding Night* eigentlich ab?**

        Das ganze findet stets Abends ab 19:00 Uhr statt. Ein Ende gibt es eigentlich nicht, open end also. Die
        Vergangenheit hat aber gezeigt, dass die meisten ca. 6 Stunden bleiben. Ergo geht das Event bis ca. 1:00
        Uhr.

        Zu Anfang gibt es eine kleine Introduction-Runde, wo sich jeder vorstellt und erklärt, worauf er oder
        sie heute Bock hat. Auf Basis dieser Runde, werden dann Gruppen erstellt, die dann schließlich gemeinsam an
        der zuvor besprochenen Sache arbeiten.

        Nach der Vorstellungsrunde setzen sich die Gruppen zusammen und diskutieren darüber, an was sie konkret über den
        Abend/die Nacht arbeiten möchten.

        Etwa zur Halbzeit des Abends, werden die Ergebnisse der Gruppen vorgestellt. Somit profitieren die
        anderen Teilnehmer von dem was du und deine Gruppe die letzten Stunden gemacht haben. Vielleicht hast du ja
        etwas in Erfahrung gebracht, was die anderen interessieren könnte. Ein geiles Tutorial oder eine Besonderheit
        oder Hindernis beim Coden entdeckt die du gerne teilen möchtest.

        **Also worauf wartest du? Code on!**

        Wenn du Coder bist, sei es Anfänger oder Profi, oder mit dem Programmieren endlich durchstarten möchtest, dann
        komme zur nächsten *Coding Night* und programmiere mit uns.
    </description>
    <url>http://www.codingnerd.de/coding-night/</url>
    <tags>
        <tag>Coding</tag>
    </tags>
    <contact>
        <facebook>https://www.facebook.com/groups/558417270913303/</facebook>
    </contact>
    <defaultmeetinglocation>
        <name>Juridicum der Goethe-Universität in Frankfurt am Main</name>
        <url>http://goo.gl/ep7QjO</url>
        <street>Senckenberganlage 31</street>
        <zip>60323</zip>
        <city>Frankfurt</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2014-05-23T19:00:00+02:00</time>
            <name>12. Coding Night [last session before summer break]</name>
            <url>http://www.meetup.com/Coding-Night-Frankfurt/events/183220672/</url>
        </meeting>
        <meeting>
            <time>2014-05-09T19:00:00+02:00</time>
            <name>11. Coding Night: code together // share knowledge // share code</name>
            <url>http://www.meetup.com/Coding-Night-Frankfurt/events/180042082/</url>
        </meeting>
        <meeting>
            <time>2014-04-25T19:00:00+02:00</time>
            <name>10. Coding Night: workshop special</name>
        </meeting>
        <meeting>
            <time>2014-04-11T19:00:00+02:00</time>
            <name>9. Coding Night</name>
            <description>
                As always, we're going to play around with code, try new stuff and extend our coding knowledge. BUT this
                time we're going to focus on programmable gadgets.

                I'm going to bring the Sphero Robot Ball to the meetup. More information about Sphero can be found here:
                http://www.gosphero.com. Further information on how to program the ball are here:
                https://developer.gosphero.com/. During the 7th Coding Night we already wrote a small program in Python
                were we let the ball move in circles and changed its colors. The repository with the code can be found
                on GitHub: https://github.com/CodingNight/SpheroPython

                Furthermore I'm going to bring Karotz (http://store.karotz.com/). Those gadgets are lent from the
                Open-Tech-School Rhein Main (http://www.opentechschool.org/rheinmain/). Thanks a lot for the support!
                In the last Coding Night Gregor brought the Cleware Traffic Light along. Information about this
                programmable gadget can be found here: http://www.cleware.net/produkte/p-clewarecontrol-E.html. For this
                project there is also a GitHub repository: https://github.com/CodingNight/cleware-hudson-jenkins

                So if you have also any other programmable gadget, you can bring it along to the Coding Night, so we
                have more toys to play with! :)
            </description>
            <url>http://www.meetup.com/Coding-Night-Frankfurt/events/174165652/</url>
        </meeting>
        <meeting>
            <time>2014-03-28T19:00:00</time>
            <name>8. Coding Night</name>
            <url>http://www.meetup.com/Coding-Night-Frankfurt/events/171554682/</url>
        </meeting>
        <meeting>
            <time>2014-01-31T19:00:00</time>
            <name>4. Coding Night</name>
        </meeting>
    </schedule>
    <team>
        <person>
            <name>Pavlos Giannakis</name>
            <url>http://www.codingnerd.de/ueber-mich/</url>
            <email>pavlos@codingnerd.de</email>
            <twitter>@coding_nerd</twitter>
        </person>
    </team>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/leanstartupcircle.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Lean Startup Circle Rhein-Main</name>
    <description>Der Lean Startup Circle Rhein-Main ist eine Gruppe Gleichgesinnter, die sich über die Ideen und
        Methoden des Lean Startup austauschen möchte. Lean Startup ist ein Vorgehen für die Realisierung von Produkten
        und Dienstleistungen unter Unsicherheit, das sich zunehmender Beliebtheit erfreut.
    </description>
    <url>https://www.xing.com/net/prib45109x/leanstartuprm</url>
    <tags>
        <tag>Lean Startup</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2014-01-29T18:30:00</time>
            <name>Januar-Treffen des Lean Startup Circles FrankfurtRheinMain</name>
            <description>Unser Januar-Treffen des Lean Startup Circles FrankfurtRheinMain findet im Co-Working-Space
                Königstein statt.

                Zunächst wird Dr. Christiane Gerigk eine kurze Einführung in das Thema "Lean Startup" geben, um auch
                Neulingen bei unseren Treffen einen thematischen Einstieg zu bieten.

                Es folgt ein Vortrag von Paul Herwarth von Bittenfeld: "Die Geschichte eines Startups - Weshalb Du
                darüber nachdenken solltest, ein "Lean Startup" zu sein".
            </description>
            <url>https://www.xing.com/events/januar-treffen-lean-startup-circles-frankfurtrheinmain-1342227</url>
            <location>
                <name>Coworking Space Königstein</name>
                <url>http://www.coworking-koenigstein.de/kontakt-und-anfahrt/#Anreise</url>
                <street>Limburger Straße 28</street>
                <zip>61462</zip>
                <city>Königstein im Taunus</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-11-12T19:15:00</time>
            <name>Lean Startup Meetup: Value Proposition Canvas für den "Market-Fit"</name>
            <description>
                Am 12. November gibt Daniel Bartel uns eine Einführung in den neuen Value Proposition Canvas mit
                anschließender Diskussion.

                **BESCHREIBUNG ZUM VORTRAG**

                Alexander Osterwalder, Autor des Buches „Business Model Generation“ ist durch das Business Model Canvas
                bekannt geworden. Das Canvas hilft u.a. Startup-Teams, als gemeinsame Sprache Geschäftsmodelle zu
                skizzieren und zu iterieren.

                Das neue „Value Proposition Canvas“, welches als „Plug-In“ zum bestehenden Canvas u.a. durch Alexander
                Osterwalder entwickelt wurde, hilft Teams bei der Erarbeitung der Nutzerversprechen, um „Market-Fit“ zu
                erlangen.

                Nach einer Einführung mit praktischen Tipps werden wir gemeinsam diese Methode diskutieren und einen
                Bezug zu Lean Startup, Customer Development &amp; Design Thinking herstellen.

                **REFERENT**

                Als ehemaliger Mitgründer eines erfolgreichen p2p-Carsharing-Startups gilt er mit KoKonsum.org als
                Experte der Sharing Economy. Als Service Design Thinker berät er und gibt als zertifizierter Trainer im
                Business Model Canvas u.a. Workshops zu den Themen Lean Startup &amp; Customer Development. Seit 2011
                organisiert &amp; moderiert er verschiedene Eventformate, u.a. Leancamps, Business Innovation Hackathons &amp;
                Startup Weekends weltweit. Daniel vertritt zudem den Bundesverbandes Deutsche Startups e.V.
            </description>
            <url>https://www.xing.com/events/lean-startup-meetup-value-proposition-canvas-market-fit-1319850</url>
            <location>
                <name>Seibert Media GmbH</name>
                <description>Ganz wichtig! Da der Veranstaltungsort in einem Einkaufszentrum ist, bitte unbedingt die
                    Wegbeschreibung anschauen.
                </description>
                <url>http://www.seibert-media.net/kontakt/wegbeschreibung/index.shtml</url>
                <twitter>@seibertmedia</twitter>
                <street>Kirchgasse 6</street>
                <zip>65185</zip>
                <city>Wiesbaden</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-09-11T19:00:00+02:00</time>
            <name>Lean Startup Circle: "Life’s too short to build something nobody wants." - Ash Maurya</name>
            <description>Mit Blick auf den Running Lean Workshop von Ash Maurya in Frankfurt wollen wir uns (noch
                einmal) näher mit seinen Methoden und Werkzeugen befassen: Lean Canvas, Lean Stack, 3 principles of
                running lean. Idealerweise sind wir im Anschluss alle so up-to-date in den Basics der Methodik, dass wir
                in seinem Workshop am 23/24.9. ein offenes Ohr für seine Beispiele, Lessons und Schlussfolgerungen
                haben. Paul Herwarth und ich werden etwas vorstellen. Bringt eure Ergänzungen und Fragen gern mit. Wenn
                es klappt, schalten wir Ash kurz zur Beantwortung von Fragen dazu.
            </description>
            <url>
                https://www.xing.com/events/lean-startup-circle-life-too-short-to-build-something-nobody-wants-ash-maurya-1282045
            </url>
            <location>
                <name>StartFFM Coworking Space</name>
                <url>http://www.start-ffm.de/</url>
                <publictransport>U-Bahn U6, Bus 34, N1, N11, N2, 34, N1, N11, N2</publictransport>
                <street>Seelenberger Str. 2</street>
                <zip>60489</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-02-25T18:30:00</time>
            <name>6. Treffen des Lean Startup Circle Rhein-Main in Wiesbaden</name>
            <url>https://www.xing.com/events/6-treffen-lean-startup-circle-rhein-main-wiesbaden-1191900</url>
            <location>
                <name>heimathafen Wiesbaden</name>
                <description>
                    Unsere Vision ist es, eine Plattform zu schaffen. Eine Plattform für Kreative &amp; Wissensarbeiter,
                    für Freiberufler &amp; Startups, für Selbstständige und Agenturen in Wiesbaden.
                </description>
                <url>http://heimathafen-wiesbaden.de/</url>
                <twitter>@heimathafenWI</twitter>
                <publictransport>Mit den Buslinien 3, 6, 16, 28, 33, 36, 60, 67 zur Haltestelle Adelheidstraße (2
                    Minuten Fußweg)
                </publictransport>
                <street>Karlstraße 22</street>
                <zip>65185</zip>
                <city>Wiesbaden</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <group>Foto: [Paul Herwarth von
            Bittenfeld](http://www.flickr.com/photos/pherwarth/7179080251/in/set-72157630046900577/)
        </group>
    </photocredits>
</usergroup>
