=== coderbyheart/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="usergroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="nonEmptyString">
					<xs:annotation>
						<xs:documentation>Vollständiger Name der Usergroup in Langfassung,
							z.B. Python UserGroup RheinMain
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="nickname" type="nonEmptyString" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="nonEmptyString">
					<xs:annotation>
						<xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
							ausführlich sein.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="url" type="xs:anyURI">
					<xs:annotation>
						<xs:documentation>Die URL der Homepage der Usergroup.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="tags">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tag" type="xs:token" maxOccurs="3"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contact" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mailinglist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="label" type="nonEmptyString"></xs:element>
										<xs:element name="description" type="nonEmptyString" minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="email" minOccurs="0" type="email"></xs:element>
							<xs:element name="twitter" minOccurs="0" type="twitter"></xs:element>
							<xs:element name="hashtag" minOccurs="0" type="hashtag"></xs:element>
							<xs:element name="facebook" minOccurs="0" type="facebook"></xs:element>
							<xs:element name="googleplus" minOccurs="0" type="googleplus"></xs:element>
							<xs:element name="xing" minOccurs="0" type="xing"></xs:element>
							<xs:element name="irc" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="server" type="xs:anyURI"></xs:element>
										<xs:element name="room" type="nonEmptyString"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="xmpp" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="server" type="xs:anyURI"></xs:element>
										<xs:element name="room" type="nonEmptyString"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="schedule" minOccurs="0">
					<xs:complexType>
						<xs:annotation>
							<xs:documentation>Liefert Information zu den nächsten Treffen der
								UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
								werden, oder die Meetings werden manuell konfiguriert.
							</xs:documentation>
						</xs:annotation>
						<xs:choice>
							<xs:element name="ical" type="xs:anyURI"></xs:element>
							<xs:element name="meeting" maxOccurs="unbounded" type="meeting"></xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="sponsors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sponsor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="nonEmptyString"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="photocredits" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="logo" type="nonEmptyString"
								minOccurs="0"></xs:element>
							<xs:element name="group" type="nonEmptyString"
								minOccurs="0"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="email">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für E-Mail Adressen
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="twitter">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Twitter-Handles
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="@[a-zA-Z0-9_]{1,15}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="hashtag">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Hashtags
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#[a-zA-Z0-9]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="facebook">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf facebook.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.facebook\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="xing">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf xing.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.xing\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="googleplus">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf Google+
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://plus\.google\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
	<xs:simpleType name="nonEmptyString">
		<xs:annotation>
			<xs:documentation>Ein nicht-leerer String</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="meeting">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Meetings (zukünftige
				und vergangene)
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="time" type="xs:dateTime"></xs:element>
			<xs:element name="name" type="nonEmptyString"></xs:element>
			<xs:element name="description" type="nonEmptyString" minOccurs="0"></xs:element>
			<xs:element name="url" type="xs:anyURI" minOccurs="0"></xs:element>
			<xs:element name="location" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. OFfenraum Coworking Space
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="description" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. OFfenraum ist ein Coworking Space im
									Rhein-Main-Gebiet südlich von Frankfurt in Offenbach am Main,
									in der Nähe des Hauptbahnhofs, Hassia Fabrik und
									Stadtkrankenhaus.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="url" type="xs:anyURI" minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. http://offenraum.de/#lage
								</xs:documentation>
							</xs:annotation>
						</xs:element>
                        <xs:element name="twitter" type="twitter" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>z.B. @OFfenraum
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
						<xs:element name="publictransport" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Regionalbahn HBf Offenbach. S1, S2, S8,
									S9 Offenbach Markplatz. Bus 104 Haydnstraße.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="street" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. Senefelderstr. 63</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="zip" type="plz">
							<xs:annotation>
								<xs:documentation>z.B. 63069</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="city" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. Offenbach</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="region" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Hessen</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="country" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Deutschland</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="plz">
		<xs:annotation>
			<xs:documentation>Eine deutsche PLZ</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="10000"></xs:minInclusive>
			<xs:maxInclusive value="99999"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== coderbyheart/ugrm-data/usergroup/wmfra.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Webmontag Frankfurt</name>
    <nickname>WMFRA</nickname>
    <description>Der Webmontag Frankfurt bringt Anwender, Entwickler, Gründer, Unternehmer, Venture Capitalists,
        Forscher, Web-Pioniere, Blogger, Podcaster, Designer und sonstige Interessenten zum Thema Web 2.0 zusammen. Die
        Veranstaltung ist kostenlos und findet immer am 2. Montag im Monat statt.
    </description>
    <url>http://www.wmfra.de/</url>
    <tags>
        <tag>Internet</tag>
    </tags>
    <contact>
        <twitter>@wmfra</twitter>
        <hashtag>#wmfra</hashtag>
        <facebook>http://www.facebook.com/wmfra</facebook>
        <googleplus>https://plus.google.com/110561795970285494597</googleplus>
    </contact>
    <defaultmeetinglocation>
        <name>Brotfabrik Hausen e.V.</name>
        <description>Die Brotfabrik im Stadtteil Hausen von Frankfurt am Main ist ein selbstverwaltetes Zentrum in einer
            ehemaligen Brotfabrik (bis 1962). Insgesamt elf verschiedene Projekte teilen sich fast 1500 m².
            Neben zwei Bühnen gibt es noch einen großen Veranstaltungssaal in dem regelmässig die Konzerte stattfindent,
            zwei Lokale mit gutem Essen, drei psychosoziale Projekte, eine Werbeagentur und ein Atelier.
        </description>
        <url>http://www.brotfabrik.info/</url>
        <twitter>@brotfabrik</twitter>
        <publictransport>U6/U7 in Richtung Heerstraße/Hausen. Nachtbus: N6/7. Haltestellen: Industriehof / Fischstein /
            Große Nelkenstraße
        </publictransport>
        <street>Bachmannstr. 2-4</street>
        <zip>60488</zip>
        <city>Frankfurt</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2014-01-13T19:00:00</time>
            <name>Webmontag #56: Aufbruch</name>
            <url>http://www.wmfra.de/programm/webmontag-frankfurt-56-schwerpunkt-aufbruch.html</url>
        </meeting>
        <meeting>
            <time>2014-02-10T19:00:00</time>
            <name>Webmontag #57: Sicherheit</name>
            <url>http://www.wmfra.de/programm/webmontag-frankfurt-57-schwerpunkt-sicherheit.html</url>
        </meeting>
        <meeting>
            <time>2014-03-10T19:00:00</time>
            <name>Webmontag #58: Un:Normal</name>
            <url>http://www.wmfra.de/programm/webmontag-frankfurt-58-schwerpunkt-un-normal.html</url>
        </meeting>
        <meeting>
            <time>2014-05-12T19:00:00+02:00</time>
            <name>Webmontag #60: Wahrheit oder Pflicht</name>
        </meeting>
        <meeting>
            <time>2014-06-16T19:00:00+02:00</time>
            <name>Webmontag #61: Summer Games</name>
        </meeting>
        <meeting>
            <time>2014-07-14T19:00:00+02:00</time>
            <name>Webmontag #62: Was Hänschen nicht lernt…</name>
        </meeting>
        <meeting>
            <time>2014-08-11T19:00:00+02:00</time>
            <name>Webmontag #63: World Wide Web</name>
        </meeting>
        <meeting>
            <time>2014-09-08T19:00:00+02:00</time>
            <name>Webmontag #64: Bei Risiken und Nebenwirkungen</name>
        </meeting>
        <meeting>
            <time>2014-10-13T19:00:00+02:00</time>
            <name>Webmontag #65: Der Geist in der Maschine</name>
        </meeting>
        <meeting>
            <time>2014-11-10T19:00:00</time>
            <name>Webmontag #66: Geld oder Liebe</name>
        </meeting>
        <meeting>
            <time>2014-12-08T19:00:00</time>
            <name>Webmontag #67: Super Webmontag 67</name>
        </meeting>
        <meeting>
            <time>2014-04-14T19:00:00+02:00</time>
            <name>Webmontag #59: Ignite</name>
            <description>15 Sekunden bestimmen den Rhythmus des nächsten Webmontag Frankfurt: 15 Sekunden – genau so
                lange hat jeder Sprecher Zeit, jede seiner 20 Vortragsfolien in einer 5-minütigen Präsentation zu
                kommentieren, bevor automatisch auf die nächste Folie gewechselt wird.

                Dieses Veranstaltungsformat nennt sich Ignite und lässt die Sprecher das Wesentliche in kürzester Zeit
                auf den Punkt bringen. Den Zuhörern bringt es ein Feuerwerk an Inspirationen zu zahlreichen
                interessanten Themen rund um’s Web.
            </description>
            <url>http://www.wmfra.de/programm/webmontag-frankfurt-59-ignite.html</url>
        </meeting>
        <meeting>
            <time>2013-03-11T19:00:00</time>
            <name>Webmontag #46: Cloud &amp; Big Data</name>
        </meeting>
        <meeting>
            <time>2013-04-08T19:00:00+02:00</time>
            <name>Webmontag #47: ignite</name>
        </meeting>
        <meeting>
            <time>2013-05-13T19:00:00+02:00</time>
            <name>Webmontag #48: Medien</name>
        </meeting>
        <meeting>
            <time>2013-06-10T19:00:00+02:00</time>
            <name>Webmontag #49: StartUp</name>
        </meeting>
        <meeting>
            <time>2013-07-08T19:00:00+02:00</time>
            <name>Webmontag #50: Code</name>
        </meeting>
        <meeting>
            <time>2013-08-12T19:00:00+02:00</time>
            <name>Webmontag Frankfurt #51, Schwerpunkt Neuland</name>
            <description>PRISM, Tempora, Supergrundrecht, Datenschutz und das alles im Neuland. Aus aktuellem Anlass
                ändern wir unser Programm für den Monat August und laden Sprecher ein, die euch zum Thema Datenschutz,
                Netzpolitik und Internet auf den neusten Stand bringen und euch praktische Tipps im Umgang mit euren
                Daten geben.
            </description>
            <url>http://www.wmfra.de/programm/webmontag-frankfurt-51-schwerpunkt-neuland.html</url>
        </meeting>
        <meeting>
            <time>2013-09-09T19:00:00+02:00</time>
            <name>Webmontag #52: Mobility</name>
            <description>Taxi, Bahn, Flug und sogar die Raumfahrt, das breite Spektrum der Mobilität kombiniert mit
                digitaler Technologie, sozialen Medien und dem vernetzten Leben verspricht Spannung, Leidenschaft und
                Innovationen. An diesem Abend möchten wir euch einige interessante Aspekte der Mobilität in 2013 näher
                bringen.
            </description>
        </meeting>
        <meeting>
            <time>2013-10-14T19:00:00+02:00</time>
            <name>Webmontag #53: ignite</name>
        </meeting>
        <meeting>
            <time>2013-11-11T19:00:00</time>
            <name>Webmontag #54: Future of Work</name>
        </meeting>
        <meeting>
            <time>2013-12-09T19:00:00</time>
            <name>Webmontag #55: RheinMainRocks</name>
        </meeting>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/cccffm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Chaos Computer Club Frankfurt e.V.</name>
    <nickname>CCCFFM</nickname>
    <description>Wir sind eine Gruppe von Leuten, die sich teilweise schon seit Jahren wöchentlich zum Meinungs-,
        Erfahrungs- und Wissensaustausch treffen. Themen sind hierbei im Wesentlichen Computer und digitale
        Kommunikation, Technik allgemein, gesellschaftliche Auswirkungen und Veränderungen hierdurch, Kunst, Kultur und
        Bildung im technischen Umfeld, Spaß am Gerät (siehe dazu auch unsere Satzung).
        Dazu treffen wir uns jeden Donnerstag öffentlich im Hackquarter wozu auch Nicht-Mitglieder jederzeit willkommen
        sind – wir freuen uns immer über neue Leute! An anderen Tagen unternehmen wir auch schon mal spontan was in
        kleineren Gruppen.
        Seit November 2010 haben wir unseren eigenen Hackerspace (das Hackquarter) in der Kommunikationsfabrik. Hier
        kann man zusammen löten, diskutieren, klönen, ohne daß man kurz nach Mitternacht nach Hause geschickt wird, und
        kann z.B. während der Laufzeit von Projekten auch schon mal Sachen dort lassen.
        Als Erfahrungsaustauschkreis (Erfa) des CCC e.V. pflegen wir auch den Austausch mit anderen Erfas, Chaostreffs
        und Gruppen der Chaos-Familie, nehmen mehr oder weniger aktiv an vielen Chaos-Events teil und führen mit Anderen
        aus der Region die jährlichen MetaRheinMain Chaosdays als Mitveranstalter durch. Für nähere Infos könnt Ihr uns
        am besten im IRC besuchen oder an unserer Mailingliste teilnehmen. Oder Ihr kommt einfach mal donnerstags ins
        Hackquarter.
    </description>
    <url>http://ccc-ffm.de/</url>
    <tags>
        <tag>Chaos-Computer-Club</tag>
        <tag>Hackerspace</tag>
        <tag>Technik-Kultur-Gesellschaft</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>http://lists.ccc-ffm.de/listinfo/public</url>
            <label>öffentliche Mailingliste</label>
        </mailinglist>
        <twitter>@cccffm</twitter>
    </contact>
    <defaultmeetinglocation>
        <name>CCCFFM - HQ</name>
        <description>Unsere Treffen finden in unserem Hackerspace dem sog. HQ statt</description>
        <url>https://ccc-ffm.de/hackerspace/</url>
        <publictransport>Vom Hauptbahnhof kommend erreicht man das Hackquarter mit den 
            Staßenbahnlinien 11 (Richtung Zuckschwerdtstraße) oder 21 (Richtung Mönchhofstraße oder Nied Kirche)  
            bis zur Haltestelle Mönchhofstraße.
            An der Ampel, die sich direkt an die Haltestelle anschließt überquert man die Mainzer Straße,
            nach rechts (von der Tram kommend) und folgt dann der Schmidtstraße für ca. 300 Meter. 
            Schließlich erreicht man eine große Einfahrt mit zwei (offenen) Schranken. Dort läuft man in den Hof und geht in den “Haupteingang”
        
            Kommt man mit der S3, S4, S5 oder S6  fährt man mit der S-Bahn bis zur Haltestelle Galluswarte und steigt dort in eine der oben genannten Straßenbahnen um.

           Aus der Innenstadt kommend ist es sinnvoll mit einer der genannten S-Bahnen bis zur Galluswarte zu fahren und dort in eine der entsprechenden Straßenbahnen umzusteigen.
                   
        </publictransport>
        <street>Schmidtstraße 12</street>
        <zip>60326</zip>
        <city>Frankfurt am Main</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <ical>https://ccc-ffm.de/feed/my-calendar-ics/</ical>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/fradev.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Frankfurt Developers</name>
    <nickname>fradev</nickname>
    <description>
        One big group focusing on coding. We gather all passionated developers in the Frankfurt area who love to code, want to learn something new and want to connect.
    </description>
    <url>http://codingnight.co/</url>
    <tags>
        <tag>Code</tag>
    </tags>
    <contact>
        <meetup>http://www.meetup.com/de-DE/Frankfurt-Developers/</meetup>
    </contact>
    <schedule>
        <ical>http://www.meetup.com/de-DE/Frankfurt-Developers/events/ical</ical>
    </schedule>
    <team>
        <person>
            <name>Pavlos Giannakis</name>
            <url>http://codenomads.co/#about-us</url>
            <email>pavlos@codenomads.co</email>
            <twitter>@coding_nerd</twitter>
        </person>
    </team>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/mongodbfrm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>MongoDB User Group Frankfurt Rhein-Main</name>
    <description>Ziel dieser Gruppe ist der regelmäßige Informationsaustausch zwischen MongoDB-Usern aus dem Großraum
        Frankfurt (und auch gerne darüber hinaus). Wir wollen im Rahmen einer Vortragsserie unsere MongoDB-Projekte
        vorstellen, diskutieren und unsere Erfahrungen weitergeben.
    </description>
    <url>http://www.meetup.com/Frankfurt-Rhine-Main-MongoDB-User-Group/</url>
    <!-- url>https://www.xing.com/net/mongodb-ffm/</url -->
    <tags>
        <tag>MongoDB</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2013-07-30T19:00:00+02:00</time>
            <name>#2 - Sommer-Stammtisch</name>
            <url>https://www.xing.com/events/mug-rhein-main-2-sommer-stammtisch-1274536</url>
            <location>
                <name>DEPOT 1899</name>
                <url>http://www.depot1899.de/</url>
                <foursquare>https://de.foursquare.com/v/depot-1899/4b0adcb2f964a520152923e3</foursquare>
                <street>Textorstraße 33</street>
                <zip>60594</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-04-24T19:00:00+02:00</time>
            <name>#1 - MongoDB Replication/Sharding</name>
            <url>http://www.meetup.com/Frankfurt-Rhine-Main-MongoDB-User-Group/events/111519292/</url>
            <location>
                <name>Ibis Hotel Mainz City</name>
                <street>Holzhofstrasse 2</street>
                <zip>55116</zip>
                <city>Mainz</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-03-20T19:00:00</time>
            <name>MongoDB Stammtisch</name>
            <url>https://www.xing.com/events/mongodb-stammtisch-1220268</url>
            <location>
                <name>Kaminzimmer im Eschenheimer</name>
                <url>www.eschenheimer.de</url>
                <street>Eschenheimer Turm</street>
                <zip>60318</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/jugda.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
  <name>Java User Group Darmstadt</name>
  <nickname>JUGDA</nickname>
  <description>Die JUG DA ist eine offene Non-Profit-Community mit dem Ziel
		sich über aktuelle Themen zur Anwendung von Java Technologie
		auszutauschen – und darüber hinaus einen Blick auf andere (VM-) Sprachen
		und Technologien wie JavaScript, Closure, oder Maven zu werfen.
    </description>
  <url>http://www.jug-da.de</url>
  <tags>
    <tag>Java</tag>
    <tag>JavaScript</tag>
    <tag>Spring</tag>
    <tag>Java EE</tag>
    <tag>JavaFX</tag>
  </tags>
  <contact>
    <mailinglist>
      <url>http://groups.google.com/group/jug-da</url>
      <label>Mailingliste</label>
      <description>Termine und News</description>
    </mailinglist>
    <twitter>@JUG_DA</twitter>
  </contact>
  <schedule>
    <ical>https://www.google.com/calendar/ical/q5vt4sq9qt7i8bjsdfgshg4b94%40group.calendar.google.com/public/basic.ics</ical>
  </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/wpfra.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" female="false">
    <name>WordPress Meetup Frankfurt</name>
    <nickname>WPFRA</nickname>
    <description>Das WordPress Meetup Frankfurt ist ein lockeres Treffen von WordPress-Fans, die sich mit WordPress
        beschäftigen. Der ungezwungene Austausch zum Thema WordPress steht im Vordergrund, daneben gehören auch kurze,
        themenbezogene Talks zum Programm. Willkommen ist jede und jeder, die oder der sich für WordPress interessiert –
        egal, ob Anwender, Designer, Entwickler, SEOs, Marketeers oder Hobby-Blogger. Unsere WP Meetups sind
        ausdrücklich keine Akquise-Veranstaltungen! Wir legen Wert auf einen offenen, ungezwungenen Austausch und
        bitten, dass alle Teilnehmenden dies berücksichtigen.
    </description>
    <url>https://wpmeetup-frankfurt.de/</url>
    <tags>
        <tag>WordPress</tag>
        <tag>PHP</tag>
    </tags>
    <contact>
        <twitter>@WPFRA</twitter>
        <hashtag>#WPFRA</hashtag>
        <meetup>http://www.meetup.com/wpmeetup-frankfurt/</meetup>
    </contact>
    <defaultmeetinglocation>
        <name>moenus+friends</name>
        <url>https://moenus.net/</url>
	<publictransport>Die Räumlichkeiten von moenus+friends finden sich in der Nähe vom Zoo Frankfurt/Ostendstraße.</publictransport>
        <street>Friedberger Anlage 8 (Hinterhaus)</street>
        <zip>60314</zip>
        <city>Frankfurt</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <ical>https://www.meetup.com/wpmeetup-frankfurt/events/ical</ical>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/pystada.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" female="false">
    <name>Python Stammtisch Darmstadt</name>
    <nickname>PyStaDa</nickname>
    <description markdown="true">In Darmstadt gibt es seit Februar 2014 einen Stammtisch zum Thema Python.

	Wir verstehen uns als lockere Gemeinschaft, die sich zum Austausch über Projekte, Probleme und Ideen Rund um die Programmiersprache Python trifft. Der Plan ist immer mal wieder einen Vortrag über ein Python Projekt oder ein Software-Handwerks-Thema wie Version Control, Projektmanagement oder Ähnliches zu haben.

        Die Treffen finden alle zwei Wochen in der so genannten Trollhöhle statt und sind für alle Interessierten offen.
	Sie haben keine festgelegte Agenda, alles rund um Python geht.
	In Wochen in denen die [PyUGRM](http://usergroups.rheinmainrocks.de/~pyugrm) statt findet, fallen die Treffen aus.
    </description>
    <url>http://pystada.github.io/</url>
    <tags>
        <tag>Python</tag>
    </tags>
    <contact>
        <twitter>@PyStaDa</twitter>
        <hashtag>#PyStaDa</hashtag>
        <mailinglist>
            <url>https://lists.chaos-darmstadt.de/mailman/listinfo/pystada</url>
            <label>Mailingliste</label>
            <description>Mailingliste für Termin-Ankündigungen und Austausch.</description>
        </mailinglist>
    </contact>
    <defaultmeetinglocation>
        <name>Trollhöhle des Chaos Darmstadt</name>
        <url>https://wiki.chaos-darmstadt.de/wiki/Trollh%C3%B6hle</url>
        <foursquare>https://foursquare.com/v/trollh%C3%B6hle/5155a0e7e4b0d9a3f3dcde86</foursquare>
        <twitter>@trollhoehle</twitter>
        <street>Wilhelm-Leuschner-Straße 36</street>
        <zip>64293</zip>
        <city>Darmstadt</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2014-02-12T19:00:00+01:00</time>
            <name>Treffen des PyStaDa</name>
        </meeting>
        <meeting>
            <time>2014-04-09T19:30:00+02:00</time>
            <name>Treffen des PyStaDa</name>
            <url>https://pads.ccc.de/pystada-2014-04-09</url>
        </meeting>
        <meeting>
            <time>2014-04-23T19:30:00+02:00</time>
            <name>Treffen des PyStaDa</name>
        </meeting>
        <meeting>
            <time>2014-05-07T19:30:00+02:00</time>
            <name>Treffen des PyStaDa</name>
        </meeting>
    </schedule>
    <team>
        <person>
            <name>Zoran Zaric</name>
            <twitter>@zoranzaric</twitter>
        </person>
        <person>
            <name>Niko Wenselowski</name>
            <twitter>@amokleben</twitter>
        </person>
    </team>
</usergroup>
