=== coderbyheart/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="usergroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="nonEmptyString">
					<xs:annotation>
						<xs:documentation>Vollständiger Name der Usergroup in Langfassung,
							z.B. Python UserGroup RheinMain
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="nickname" type="nonEmptyString" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="nonEmptyString">
					<xs:annotation>
						<xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
							ausführlich sein.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="url" type="xs:anyURI">
					<xs:annotation>
						<xs:documentation>Die URL der Homepage der Usergroup.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="tags">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tag" type="xs:token" maxOccurs="3"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contact" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mailinglist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="label" type="nonEmptyString"></xs:element>
										<xs:element name="description" type="nonEmptyString" minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="email" minOccurs="0" type="email"></xs:element>
							<xs:element name="twitter" minOccurs="0" type="twitter"></xs:element>
							<xs:element name="hashtag" minOccurs="0" type="hashtag"></xs:element>
							<xs:element name="facebook" minOccurs="0" type="facebook"></xs:element>
							<xs:element name="googleplus" minOccurs="0" type="googleplus"></xs:element>
							<xs:element name="xing" minOccurs="0" type="xing"></xs:element>
							<xs:element name="irc" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="server" type="xs:anyURI"></xs:element>
										<xs:element name="room" type="nonEmptyString"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="xmpp" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="server" type="xs:anyURI"></xs:element>
										<xs:element name="room" type="nonEmptyString"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="schedule" minOccurs="0">
					<xs:complexType>
						<xs:annotation>
							<xs:documentation>Liefert Information zu den nächsten Treffen der
								UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
								werden, oder die Meetings werden manuell konfiguriert.
							</xs:documentation>
						</xs:annotation>
						<xs:choice>
							<xs:element name="ical" type="xs:anyURI"></xs:element>
							<xs:element name="meeting" maxOccurs="unbounded" type="meeting"></xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="sponsors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sponsor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="nonEmptyString"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="photocredits" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="logo" type="nonEmptyString"
								minOccurs="0"></xs:element>
							<xs:element name="group" type="nonEmptyString"
								minOccurs="0"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="email">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für E-Mail Adressen
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="twitter">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Twitter-Handles
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="@[a-zA-Z0-9_]{1,15}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="hashtag">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Hashtags
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#[a-zA-Z0-9]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="facebook">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf facebook.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.facebook\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="xing">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf xing.com
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https*://www\.xing\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="googleplus">
        <xs:annotation>
            <xs:documentation>Definiert eine URL auf Google+
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https://plus\.google\.com/.*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
	<xs:simpleType name="nonEmptyString">
		<xs:annotation>
			<xs:documentation>Ein nicht-leerer String</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="meeting">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentyp für Meetings (zukünftige
				und vergangene)
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="time" type="xs:dateTime"></xs:element>
			<xs:element name="name" type="nonEmptyString"></xs:element>
			<xs:element name="description" type="nonEmptyString" minOccurs="0"></xs:element>
			<xs:element name="url" type="xs:anyURI" minOccurs="0"></xs:element>
			<xs:element name="location" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. OFfenraum Coworking Space
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="description" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. OFfenraum ist ein Coworking Space im
									Rhein-Main-Gebiet südlich von Frankfurt in Offenbach am Main,
									in der Nähe des Hauptbahnhofs, Hassia Fabrik und
									Stadtkrankenhaus.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="url" type="xs:anyURI" minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. http://offenraum.de/#lage
								</xs:documentation>
							</xs:annotation>
						</xs:element>
                        <xs:element name="twitter" type="twitter" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>z.B. @OFfenraum
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
						<xs:element name="publictransport" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Regionalbahn HBf Offenbach. S1, S2, S8,
									S9 Offenbach Markplatz. Bus 104 Haydnstraße.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="street" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. Senefelderstr. 63</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="zip" type="plz">
							<xs:annotation>
								<xs:documentation>z.B. 63069</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="city" type="nonEmptyString">
							<xs:annotation>
								<xs:documentation>z.B. Offenbach</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="region" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Hessen</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="country" type="nonEmptyString"
							minOccurs="0">
							<xs:annotation>
								<xs:documentation>z.B. Deutschland</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="plz">
		<xs:annotation>
			<xs:documentation>Eine deutsche PLZ</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="10000"></xs:minInclusive>
			<xs:maxInclusive value="99999"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== coderbyheart/ugrm-data/usergroup/owasp.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>OWASP Stammtisch Frankfurt</name>
    <nickname>OWASP</nickname>
    <description>OWASP ist eine unabhängige, weltweite Community mit dem Ziel, die Bedeutung der Sicherheit von Webanwendungen "sichtbar zu machen". Know-How zur Entwicklung und den Betrieb sicherer Webanwendungen zu verbreiten und frei zur Verfugung zu stellen. Wir treffen uns jeden letzten Donnerstag im Monat um 19:30 bei einem wechselnden Gastgeber. Üblicherweise gibt es mindestens einen Vortrag mit Erfahrungsaustausch. Danach begeben wir uns zum geselligen Ausklang in eine Lokalität in der Nachbarschaft.</description>
    <url>https://www.owasp.org/index.php/OWASP_German_Chapter_Stammtisch_Initiative/Frankfurt</url>
    <tags>
        <tag>Security</tag>
        <tag>OWASP</tag>
    </tags>
    <contact>
	<mailinglist>
		<url>https://lists.owasp.org/mailman/listinfo/owasp-frankfurt</url>
		<label>Mailingliste</label>
		<description>Mailingliste für Austausch und Terminankündigung</description>

	</mailinglist>
        <twitter>@OWASP_f</twitter>
    </contact>
    <schedule>
	<ical>http://www.meetup.com/de-DE/IT-Security-Stammtisch-Frankfurt-OWASP-u-w/events/</ical>
    </schedule>
    <team>
        <person>
            <name>Johannes Schönborn</name>
        </person>
    </team>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/drupal.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Drupal User Group Rhein-Main</name>
    <description>Wir treffen uns regelmäßig zu einem "Drupal Donnerstag", d.h. jeden Monat den 2. Donnerstag in jedem Monat (evtl. Ausnahmen bei Feiertagen). Abwechselnd findet dann abends ein Stammtisch oder ein Meetup mit Vorträgen statt. Am Nachmittag des Drupal-Donnerstags gibt es die Contrib-Hours zur kooperativem Weiterentwicklung von Drupal. Außerdem werden gelegentlich Sonderveranstaltungen organisiert z.B. so genannte Code-Sprints. 
    </description>
    <url>http://groups.drupal.org/rhein-main-gebiet</url>
    <tags>
        <tag>Drupal</tag>
        <tag>PHP</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2013-04-11T14:00:00+01:00</time>
            <name>Drupal-Donnerstag - Contrib Hours (abends Stammtisch, Location noch offen)</name>
            <url>http://groups.drupal.org/node/292213</url>
            <location>
                <name>paratio.com - Büro</name>
                <url>http://paratio.com/</url>
                <twitter>@C_Logemann</twitter>
                <street>Gr. Eschenheimer Str. 41a</street>
                <zip>60313</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/dmwFFM.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           plural="true">
    <name>Digital Media Women Frankfurt</name>
    <nickname>DMWffm</nickname>
    <description>Die Digital Media Women (DMW) sind ein in Hamburg gegründetes Branchennetzwerk und seit Juli 2012 ein
        eingetragener Verein. Wir arbeiten im und mit dem Netz: als Social Media Managerinnen, Web- und
        Grafikdesignerinnen, Online-Journalistinnen, Bloggerinnen, Programmiererinnen und in vielen anderen Feldern des
        World Wide Web. Unsere Arbeitsfelder sind oft Männerdomänen – doch wir wollen die Situation von Frauen in
        unseren Berufen verbessern und unsere Expertise unter Beweis stellen.

        Digital Media Women sind wissenshungrig und überzeugt, dass Wissen wächst, wenn man es teilt. Wir wollen stets
        dazu lernen. Dafür reisen wir zu Barcamps oder Branchenkonferenzen wie der re:publica, besuchen Vorträge und
        veranstalten selbst welche. Wir verstehen uns nicht bloß als passive Zuschauerinnen, wir wollen Impulse geben
        und vorne mit dabei sein. Ein wichtiges Ziel der DMW ist, mehr Frauen auf die Podien der männerdominierten
        Konferenzwelt zu bringen.

        Allen Digital Media Women steht ein dichtes Netzwerk kompetenter Frauen offen. Wir bieten neue Kontakte und
        Kommunikation auf professioneller Ebene – online und offline. Die DMW treffen sich, um gemeinsam berufliche
        Projekte voranzutreiben, neuen Input zu erfahren, einander Tipps und Empfehlungen zu geben oder einfach nur zum
        gemütlichen Austausch unter Gleichgesinnten. In der Community findest du geballte Kompetenz von inzwischen mehr
        als 600 Frauen aus ganz Deutschland – und übrigens auch Männern, die unsere Anliegen unterstützen.
    </description>
    <url>http://www.digitalmediawomen.de/</url>
    <tags>
        <tag>Media</tag>
        <tag>Women</tag>
        <tag>Digital</tag>
    </tags>
    <contact>
        <twitter>@DigiWomenDE</twitter>
        <hashtag>#dmwFFM</hashtag>
        <facebook>https://www.facebook.com/DigitalMediaWomen</facebook>
    </contact>
    <schedule>
        <meeting>
            <time>2013-03-04T19:00:00</time>
            <name>2. Gründungstreffen der #dmwffm</name>
            <description>Seit Anfang des Jahres werkeln wir daran, die #dmwffm zu einer festen, verlässlichen Größe im
                digitalen Geschehen des Rhein-Main-Gebiets zu machen. Deswegen laden wir euch ein, mit uns gemeinsam
                großartige Ideen weiterzudenken, angesagte Themen heiß zu diskutieren und neue Dinge in Bewegung zu
                bringen. Wir möchten euch gerne von unseren Ideen begeistern und mit unserem Elan anstecken – und uns
                von eurem Esprit und eurer Kreativität inspirieren lassen. Jetzt ist die richtige Zeit, um sich zu
                engagieren und einzubringen!
            </description>
            <location>
                <name>Hotwire Public Relations Germany GmbH</name>
                <description>Eingang über Weißfrauenstr. 12-16</description>
                <url>http://www.hotwirepr.de/</url>
                <twitter>@hotwired</twitter>
                <street>Friedensstr. 6-10</street>
                <zip>60311</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/pm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           plural="true">
    <name>Perl Mongers Frankfurt</name>
    <nickname>Frankfurt.pm</nickname>
    <description>Frankfurt Perl Mongers sind Menschen, die sich mit der dynamischen Programmiersprache Perl beschäftigen
        und gerne darüber reden.

        Wir treffen uns seit dem Jahr 2000 ein Mal im Monat in lockerer Atmosphäre. Der
        Schwerpunkt ist natürlich Perl, dennoch widmen wir uns auch Randgebieten und auch schon mal anderen
        Programmiersprachen.

        Wir richten uns an alle, die das Interesse haben, etwas mit Perl zu machen. Dabei spielt keine Rolle, ob
        beruflich oder nur als "Hobby". Jeder ist willkommen, der auch nur einen Funken Interesse am Programmieren mit
        Perl hat.
    </description>
    <url>http://frankfurt.pm/</url>
    <tags>
        <tag>Perl</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>http://mail.pm.org/mailman/listinfo/frankfurt-pm?language=de</url>
            <label>Mailingliste (deutsch)</label>
            <description>Such Dir aus, ob Du auf deutsch (auch hessisch wenns denn sein soll) oder englisch schreibst
                (auch kleinere Mengen Perl Code sind ganz ok), und erlaube Anderen in der Sprache zu antworten, in der
                es ihnen zu antworten gefällt.
            </description>
        </mailinglist>
        <mailinglist>
            <url>http://mail.pm.org/mailman/listinfo/frankfurt-pm?language=en</url>
            <label>Frankfurt/Main Perl Mongers Mailing List (English)</label>
            <description>Feel free to write either in English or in German (Hessian if you prefer) or post small amounts
                of Perl code there and ask for opinions. Allow others to reply in the language they prefer to reply in.
            </description>
        </mailinglist>
    </contact>
    <schedule>
        <ical>https://www.google.com/calendar/ical/1jf5irg12jgt1stlhl3ame1kh8%40group.calendar.google.com/public/basic.ics</ical>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/ceph.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Ceph Frankfurt</name>
    <description>This is a group for anyone interested in [Ceph](http://ceph.com/). All skills levels are welcome. There
        is a growing user community around this Free Software distributed storage. Participants are expected to share
        their use cases, tips and tricks, projects, have a good time in a friendly and informal atmosphere.
    </description>
    <url>http://www.meetup.com/Ceph-Frankfurt/</url>
    <tags>
        <tag>Ceph</tag>
        <tag>Distributed storage</tag>
        <tag>Cloud</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2014-02-26T19:00:00</time>
            <name>Drink and talk before the Ceph day</name>
            <description>Inktank organizes the [Ceph day February
                27th](http://www.eventbrite.com/e/ceph-day-frankfurt-tickets-10173269523). Let's take this opportunity
                to meet and discuss Ceph the evening before.
            </description>
            <url>http://www.meetup.com/Ceph-Frankfurt/events/164620852/</url>
        </meeting>
    </schedule>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/phpugrhh.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>PHP UG Rheinhessen</name>
    <nickname>PHPUGRHH</nickname>
    <description>Wir sind eine Gruppe von PHP interessierten Entwicklern. Unser Interesse besteht im gegenseitigen
        Austausch von Wissen und Erfahrungsberichten. Jeder Interessierte ist willkommen, sich bei unserer Gruppe zu
        beteiligen.
    </description>
    <url>http://www.phpug-rheinhessen.de/</url>
    <tags>
        <tag>PHP</tag>
    </tags>
    <contact>
        <twitter>@phpugrhh</twitter>
        <hashtag>#phpugrhh</hashtag>
        <facebook>http://www.facebook.com/group.php?gid=192655655785</facebook>
        <xing>https://www.xing.com/net/pri3a328cx/phpugrhh/</xing>
    </contact>
    <schedule>
        <meeting>
            <time>2013-03-05T19:00:00+01:00</time>
            <name>23. Treffen der PHP User Group Rheinhessen</name>
            <url>https://www.xing.com/events/23-treffen-phpug-rheinhessen-1205190</url>
            <location>
                <name>NIDAG GmbH</name>
                <url>http://www.nidag.com/</url>
                <publictransport>Bus 58 und 70 bis Haltestelle Feldbergplatz/Stadtwerke Mainz AG</publictransport>
                <street>Taunusstra√üe 59-61</street>
                <zip>55120</zip>
                <city>Mainz</city>
            </location>
        </meeting>
    </schedule>
    <sponsors>
        <sponsor>
            <name>netz98 new media GmbH</name>
            <url>http://www.netz98.de/</url>
        </sponsor>
        <sponsor>
            <name>NIDAG GmbH</name>
            <url>http://www.nidag.com/</url>
        </sponsor>
    </sponsors>
    <photocredits>
        <logo>Das Logo stammt von UG-Mitglied [Lukas Giebel](https://plus.google.com/102794229174790604056/about)</logo>
    </photocredits>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/usability-testessen.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Usability Testessen</name>
    <description markdown="true">Pizza, Bier und Usability Testing. 
Das Usability Testessen bringt Entwickler und Nutzer an einen Tisch. Bei Pizza, Bier und Brause werden Prototypen, Websites oder Apps auf ihre Gebrauchstauglichkeit getestet.
    </description>
    <url>http://www.usability-testessen.de/</url>
    <tags>
        <tag>Usability</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2015-05-07T19:00:00</time>
            <name>Usability Testessen bei compeople</name>
            <description>Usability Testessen bei compeople in Frankfurt! Wir freuen uns auf eure Anmeldungen und Projekte. 
            </description>
            <url>http://www.usability-testessen.de/frankfurt</url>
            <location>
                <name>compeople, Frankfurt</name>
                <url>https://www.compeople.de/</url>
                <publictransport>Bahn: U-Bahn Willy-Brandt-Platz</publictransport>
                <street>Untermainanlage 8</street>
                <zip>60329</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <logo>Logo: [usabilitytestessen](http://usability-testessen.de/)</logo>
    </photocredits>
</usergroup>

=== coderbyheart/ugrm-data/usergroup/xpugffm.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>XP User Group Frankfurt</name>
    <nickname>XPUG FFM</nickname>
    <description>Die Frankfurter XP User Group trifft sich üblicherweise 1x im Monat und beschäftigt sich mit Themen der
        agilen Software-Entwicklung aber auch mit vielem anderen in der Nähe wie Projektmanagement, Psychologisches (mit
        Bezug auf Software-Entwicklung), intensiv-technische Themen, ...
    </description>
    <url>http://agilewiki.ipponsoft.de/doku.php?id=xpug_ffm</url>
    <tags>
        <tag>Extreme Programming</tag>
        <tag>Agile</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2013-03-05T18:30:00</time>
            <name>XPUG FFM (84)</name>
            <description>Possumus Projectmanagement Games - Der außergewöhnliche Weg, Projekte zum Erfolg zu führen!
            </description>
            <url>
                https://www.xing.com/events/xpug-ffm-84-possumus-projectmanagement-games-aussergewohnliche-weg-projekte-erfolg-fuhren-1195334
            </url>
            <location>
                <name>NorCom Information Technology AG</name>
                <url>http://www.norcom.de/de/norcom-frankfurt</url>
                <twitter>@NorComAG</twitter>
                <street>Solmsstraße 14</street>
                <zip>60486</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
</usergroup>
